// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: carabiner/stash/v1/attestation.proto

package stashv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Attestation is the stored attestation metadata.
type Attestation struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AttestationId      string                 `protobuf:"bytes,1,opt,name=attestation_id,json=attestationId,proto3" json:"attestation_id,omitempty"`
	ContentHash        string                 `protobuf:"bytes,2,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	PredicateHash      string                 `protobuf:"bytes,3,opt,name=predicate_hash,json=predicateHash,proto3" json:"predicate_hash,omitempty"`
	PredicateType      string                 `protobuf:"bytes,4,opt,name=predicate_type,json=predicateType,proto3" json:"predicate_type,omitempty"`
	Signed             bool                   `protobuf:"varint,5,opt,name=signed,proto3" json:"signed,omitempty"`
	Validated          bool                   `protobuf:"varint,6,opt,name=validated,proto3" json:"validated,omitempty"`
	ValidationError    string                 `protobuf:"bytes,7,opt,name=validation_error,json=validationError,proto3" json:"validation_error,omitempty"`
	SignerIdentities   []string               `protobuf:"bytes,8,rep,name=signer_identities,json=signerIdentities,proto3" json:"signer_identities,omitempty"`
	Subjects           []*Subject             `protobuf:"bytes,9,rep,name=subjects,proto3" json:"subjects,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PredicateTimestamp *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=predicate_timestamp,json=predicateTimestamp,proto3" json:"predicate_timestamp,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Attestation) Reset() {
	*x = Attestation{}
	mi := &file_carabiner_stash_v1_attestation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attestation) ProtoMessage() {}

func (x *Attestation) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_attestation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attestation.ProtoReflect.Descriptor instead.
func (*Attestation) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_attestation_proto_rawDescGZIP(), []int{0}
}

func (x *Attestation) GetAttestationId() string {
	if x != nil {
		return x.AttestationId
	}
	return ""
}

func (x *Attestation) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *Attestation) GetPredicateHash() string {
	if x != nil {
		return x.PredicateHash
	}
	return ""
}

func (x *Attestation) GetPredicateType() string {
	if x != nil {
		return x.PredicateType
	}
	return ""
}

func (x *Attestation) GetSigned() bool {
	if x != nil {
		return x.Signed
	}
	return false
}

func (x *Attestation) GetValidated() bool {
	if x != nil {
		return x.Validated
	}
	return false
}

func (x *Attestation) GetValidationError() string {
	if x != nil {
		return x.ValidationError
	}
	return ""
}

func (x *Attestation) GetSignerIdentities() []string {
	if x != nil {
		return x.SignerIdentities
	}
	return nil
}

func (x *Attestation) GetSubjects() []*Subject {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *Attestation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Attestation) GetPredicateTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.PredicateTimestamp
	}
	return nil
}

func (x *Attestation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Subject represents a resource descriptor from an attestation.
type Subject struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Digest           map[string]string      `protobuf:"bytes,2,rep,name=digest,proto3" json:"digest,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // algorithm -> value
	Uri              string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	DownloadLocation string                 `protobuf:"bytes,4,opt,name=download_location,json=downloadLocation,proto3" json:"download_location,omitempty"`
	MediaType        string                 `protobuf:"bytes,5,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Annotations      map[string]*anypb.Any  `protobuf:"bytes,6,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key-value pairs
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_carabiner_stash_v1_attestation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_attestation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_attestation_proto_rawDescGZIP(), []int{1}
}

func (x *Subject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Subject) GetDigest() map[string]string {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *Subject) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Subject) GetDownloadLocation() string {
	if x != nil {
		return x.DownloadLocation
	}
	return ""
}

func (x *Subject) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *Subject) GetAnnotations() map[string]*anypb.Any {
	if x != nil {
		return x.Annotations
	}
	return nil
}

var File_carabiner_stash_v1_attestation_proto protoreflect.FileDescriptor

const file_carabiner_stash_v1_attestation_proto_rawDesc = "" +
	"\n" +
	"$carabiner/stash/v1/attestation.proto\x12\x12carabiner.stash.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\xaf\x04\n" +
	"\vAttestation\x12%\n" +
	"\x0eattestation_id\x18\x01 \x01(\tR\rattestationId\x12!\n" +
	"\fcontent_hash\x18\x02 \x01(\tR\vcontentHash\x12%\n" +
	"\x0epredicate_hash\x18\x03 \x01(\tR\rpredicateHash\x12%\n" +
	"\x0epredicate_type\x18\x04 \x01(\tR\rpredicateType\x12\x16\n" +
	"\x06signed\x18\x05 \x01(\bR\x06signed\x12\x1c\n" +
	"\tvalidated\x18\x06 \x01(\bR\tvalidated\x12)\n" +
	"\x10validation_error\x18\a \x01(\tR\x0fvalidationError\x12+\n" +
	"\x11signer_identities\x18\b \x03(\tR\x10signerIdentities\x127\n" +
	"\bsubjects\x18\t \x03(\v2\x1b.carabiner.stash.v1.SubjectR\bsubjects\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12K\n" +
	"\x13predicate_timestamp\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x12predicateTimestamp\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9d\x03\n" +
	"\aSubject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12?\n" +
	"\x06digest\x18\x02 \x03(\v2'.carabiner.stash.v1.Subject.DigestEntryR\x06digest\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\x12+\n" +
	"\x11download_location\x18\x04 \x01(\tR\x10downloadLocation\x12\x1d\n" +
	"\n" +
	"media_type\x18\x05 \x01(\tR\tmediaType\x12N\n" +
	"\vannotations\x18\x06 \x03(\v2,.carabiner.stash.v1.Subject.AnnotationsEntryR\vannotations\x1a9\n" +
	"\vDigestEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aT\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01B\xcf\x01\n" +
	"\x16com.carabiner.stash.v1B\x10AttestationProtoP\x01Z9github.com/carabiner-dev/stash/carabiner/stash/v1;stashv1\xa2\x02\x03CSX\xaa\x02\x12Carabiner.Stash.V1\xca\x02\x12Carabiner\\Stash\\V1\xe2\x02\x1eCarabiner\\Stash\\V1\\GPBMetadata\xea\x02\x14Carabiner::Stash::V1b\x06proto3"

var (
	file_carabiner_stash_v1_attestation_proto_rawDescOnce sync.Once
	file_carabiner_stash_v1_attestation_proto_rawDescData []byte
)

func file_carabiner_stash_v1_attestation_proto_rawDescGZIP() []byte {
	file_carabiner_stash_v1_attestation_proto_rawDescOnce.Do(func() {
		file_carabiner_stash_v1_attestation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carabiner_stash_v1_attestation_proto_rawDesc), len(file_carabiner_stash_v1_attestation_proto_rawDesc)))
	})
	return file_carabiner_stash_v1_attestation_proto_rawDescData
}

var file_carabiner_stash_v1_attestation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_carabiner_stash_v1_attestation_proto_goTypes = []any{
	(*Attestation)(nil),           // 0: carabiner.stash.v1.Attestation
	(*Subject)(nil),               // 1: carabiner.stash.v1.Subject
	nil,                           // 2: carabiner.stash.v1.Subject.DigestEntry
	nil,                           // 3: carabiner.stash.v1.Subject.AnnotationsEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 5: google.protobuf.Any
}
var file_carabiner_stash_v1_attestation_proto_depIdxs = []int32{
	1, // 0: carabiner.stash.v1.Attestation.subjects:type_name -> carabiner.stash.v1.Subject
	4, // 1: carabiner.stash.v1.Attestation.created_at:type_name -> google.protobuf.Timestamp
	4, // 2: carabiner.stash.v1.Attestation.predicate_timestamp:type_name -> google.protobuf.Timestamp
	4, // 3: carabiner.stash.v1.Attestation.updated_at:type_name -> google.protobuf.Timestamp
	2, // 4: carabiner.stash.v1.Subject.digest:type_name -> carabiner.stash.v1.Subject.DigestEntry
	3, // 5: carabiner.stash.v1.Subject.annotations:type_name -> carabiner.stash.v1.Subject.AnnotationsEntry
	5, // 6: carabiner.stash.v1.Subject.AnnotationsEntry.value:type_name -> google.protobuf.Any
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_carabiner_stash_v1_attestation_proto_init() }
func file_carabiner_stash_v1_attestation_proto_init() {
	if File_carabiner_stash_v1_attestation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carabiner_stash_v1_attestation_proto_rawDesc), len(file_carabiner_stash_v1_attestation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_carabiner_stash_v1_attestation_proto_goTypes,
		DependencyIndexes: file_carabiner_stash_v1_attestation_proto_depIdxs,
		MessageInfos:      file_carabiner_stash_v1_attestation_proto_msgTypes,
	}.Build()
	File_carabiner_stash_v1_attestation_proto = out.File
	file_carabiner_stash_v1_attestation_proto_goTypes = nil
	file_carabiner_stash_v1_attestation_proto_depIdxs = nil
}
