// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: carabiner/stash/v1/filters.proto

package stashv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Filters for querying attestations.
type Filters struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PredicateType    string                 `protobuf:"bytes,1,opt,name=predicate_type,json=predicateType,proto3" json:"predicate_type,omitempty"`
	SubjectName      string                 `protobuf:"bytes,2,opt,name=subject_name,json=subjectName,proto3" json:"subject_name,omitempty"`
	SubjectDigest    map[string]string      `protobuf:"bytes,3,rep,name=subject_digest,json=subjectDigest,proto3" json:"subject_digest,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // algorithm -> value
	SubjectUri       string                 `protobuf:"bytes,4,opt,name=subject_uri,json=subjectUri,proto3" json:"subject_uri,omitempty"`
	SubjectNameRegex string                 `protobuf:"bytes,5,opt,name=subject_name_regex,json=subjectNameRegex,proto3" json:"subject_name_regex,omitempty"` // Max 256 chars
	SubjectUriRegex  string                 `protobuf:"bytes,6,opt,name=subject_uri_regex,json=subjectUriRegex,proto3" json:"subject_uri_regex,omitempty"`    // Max 256 chars
	SignerIdentity   string                 `protobuf:"bytes,7,opt,name=signer_identity,json=signerIdentity,proto3" json:"signer_identity,omitempty"`
	SignedOnly       bool                   `protobuf:"varint,8,opt,name=signed_only,json=signedOnly,proto3" json:"signed_only,omitempty"`
	ValidatedOnly    bool                   `protobuf:"varint,9,opt,name=validated_only,json=validatedOnly,proto3" json:"validated_only,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Filters) Reset() {
	*x = Filters{}
	mi := &file_carabiner_stash_v1_filters_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filters) ProtoMessage() {}

func (x *Filters) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_filters_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filters.ProtoReflect.Descriptor instead.
func (*Filters) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_filters_proto_rawDescGZIP(), []int{0}
}

func (x *Filters) GetPredicateType() string {
	if x != nil {
		return x.PredicateType
	}
	return ""
}

func (x *Filters) GetSubjectName() string {
	if x != nil {
		return x.SubjectName
	}
	return ""
}

func (x *Filters) GetSubjectDigest() map[string]string {
	if x != nil {
		return x.SubjectDigest
	}
	return nil
}

func (x *Filters) GetSubjectUri() string {
	if x != nil {
		return x.SubjectUri
	}
	return ""
}

func (x *Filters) GetSubjectNameRegex() string {
	if x != nil {
		return x.SubjectNameRegex
	}
	return ""
}

func (x *Filters) GetSubjectUriRegex() string {
	if x != nil {
		return x.SubjectUriRegex
	}
	return ""
}

func (x *Filters) GetSignerIdentity() string {
	if x != nil {
		return x.SignerIdentity
	}
	return ""
}

func (x *Filters) GetSignedOnly() bool {
	if x != nil {
		return x.SignedOnly
	}
	return false
}

func (x *Filters) GetValidatedOnly() bool {
	if x != nil {
		return x.ValidatedOnly
	}
	return false
}

// Cursor for pagination.
type Cursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        string                 `protobuf:"bytes,2,opt,name=offset,proto3" json:"offset,omitempty"` // Opaque cursor token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_carabiner_stash_v1_filters_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_filters_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_filters_proto_rawDescGZIP(), []int{1}
}

func (x *Cursor) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Cursor) GetOffset() string {
	if x != nil {
		return x.Offset
	}
	return ""
}

var File_carabiner_stash_v1_filters_proto protoreflect.FileDescriptor

const file_carabiner_stash_v1_filters_proto_rawDesc = "" +
	"\n" +
	" carabiner/stash/v1/filters.proto\x12\x12carabiner.stash.v1\"\xd8\x03\n" +
	"\aFilters\x12%\n" +
	"\x0epredicate_type\x18\x01 \x01(\tR\rpredicateType\x12!\n" +
	"\fsubject_name\x18\x02 \x01(\tR\vsubjectName\x12U\n" +
	"\x0esubject_digest\x18\x03 \x03(\v2..carabiner.stash.v1.Filters.SubjectDigestEntryR\rsubjectDigest\x12\x1f\n" +
	"\vsubject_uri\x18\x04 \x01(\tR\n" +
	"subjectUri\x12,\n" +
	"\x12subject_name_regex\x18\x05 \x01(\tR\x10subjectNameRegex\x12*\n" +
	"\x11subject_uri_regex\x18\x06 \x01(\tR\x0fsubjectUriRegex\x12'\n" +
	"\x0fsigner_identity\x18\a \x01(\tR\x0esignerIdentity\x12\x1f\n" +
	"\vsigned_only\x18\b \x01(\bR\n" +
	"signedOnly\x12%\n" +
	"\x0evalidated_only\x18\t \x01(\bR\rvalidatedOnly\x1a@\n" +
	"\x12SubjectDigestEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"6\n" +
	"\x06Cursor\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\tR\x06offsetB\xcb\x01\n" +
	"\x16com.carabiner.stash.v1B\fFiltersProtoP\x01Z9github.com/carabiner-dev/stash/carabiner/stash/v1;stashv1\xa2\x02\x03CSX\xaa\x02\x12Carabiner.Stash.V1\xca\x02\x12Carabiner\\Stash\\V1\xe2\x02\x1eCarabiner\\Stash\\V1\\GPBMetadata\xea\x02\x14Carabiner::Stash::V1b\x06proto3"

var (
	file_carabiner_stash_v1_filters_proto_rawDescOnce sync.Once
	file_carabiner_stash_v1_filters_proto_rawDescData []byte
)

func file_carabiner_stash_v1_filters_proto_rawDescGZIP() []byte {
	file_carabiner_stash_v1_filters_proto_rawDescOnce.Do(func() {
		file_carabiner_stash_v1_filters_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carabiner_stash_v1_filters_proto_rawDesc), len(file_carabiner_stash_v1_filters_proto_rawDesc)))
	})
	return file_carabiner_stash_v1_filters_proto_rawDescData
}

var file_carabiner_stash_v1_filters_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_carabiner_stash_v1_filters_proto_goTypes = []any{
	(*Filters)(nil), // 0: carabiner.stash.v1.Filters
	(*Cursor)(nil),  // 1: carabiner.stash.v1.Cursor
	nil,             // 2: carabiner.stash.v1.Filters.SubjectDigestEntry
}
var file_carabiner_stash_v1_filters_proto_depIdxs = []int32{
	2, // 0: carabiner.stash.v1.Filters.subject_digest:type_name -> carabiner.stash.v1.Filters.SubjectDigestEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_carabiner_stash_v1_filters_proto_init() }
func file_carabiner_stash_v1_filters_proto_init() {
	if File_carabiner_stash_v1_filters_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carabiner_stash_v1_filters_proto_rawDesc), len(file_carabiner_stash_v1_filters_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_carabiner_stash_v1_filters_proto_goTypes,
		DependencyIndexes: file_carabiner_stash_v1_filters_proto_depIdxs,
		MessageInfos:      file_carabiner_stash_v1_filters_proto_msgTypes,
	}.Build()
	File_carabiner_stash_v1_filters_proto = out.File
	file_carabiner_stash_v1_filters_proto_goTypes = nil
	file_carabiner_stash_v1_filters_proto_depIdxs = nil
}
