// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: carabiner/stash/v1/namespace.proto

package stashv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Namespace is a folder-like grouping of an organization's attestations and
// policies. The default namespace has the empty name.
type Namespace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace name (empty string = default namespace).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Public opens the namespace's attestations to anyone: reads pass for a
	// caller with no token, and for one whose token holds no permission on
	// the organization. Nothing else is public.
	Public    bool                   `protobuf:"varint,2,opt,name=public,proto3" json:"public,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// attestation_count is how many attestations the namespace holds. Set
	// only when the request asked for counts (with_counts).
	AttestationCount *int64 `protobuf:"varint,5,opt,name=attestation_count,json=attestationCount,proto3,oneof" json:"attestation_count,omitempty"`
	// policy_count is how many policy documents (every stored version) the
	// namespace holds. Set only when the request asked for counts.
	PolicyCount *int64 `protobuf:"varint,6,opt,name=policy_count,json=policyCount,proto3,oneof" json:"policy_count,omitempty"`
	// Organization ID (the organization handle).
	OrgId         string `protobuf:"bytes,10,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_namespace_proto_rawDescGZIP(), []int{0}
}

func (x *Namespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Namespace) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *Namespace) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Namespace) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Namespace) GetAttestationCount() int64 {
	if x != nil && x.AttestationCount != nil {
		return *x.AttestationCount
	}
	return 0
}

func (x *Namespace) GetPolicyCount() int64 {
	if x != nil && x.PolicyCount != nil {
		return *x.PolicyCount
	}
	return 0
}

func (x *Namespace) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// CreateNamespaceRequest creates a namespace.
type CreateNamespaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace name (must be a valid namespace name; not the default).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Whether to create the namespace public (see Namespace.public).
	Public bool `protobuf:"varint,2,opt,name=public,proto3" json:"public,omitempty"`
	// Organization ID (required, must be valid DNS hostname).
	OrgId         string `protobuf:"bytes,10,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNamespaceRequest) Reset() {
	*x = CreateNamespaceRequest{}
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNamespaceRequest) ProtoMessage() {}

func (x *CreateNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNamespaceRequest.ProtoReflect.Descriptor instead.
func (*CreateNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_namespace_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNamespaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNamespaceRequest) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *CreateNamespaceRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// CreateNamespaceResponse carries the created namespace.
type CreateNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *Namespace             `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNamespaceResponse) Reset() {
	*x = CreateNamespaceResponse{}
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNamespaceResponse) ProtoMessage() {}

func (x *CreateNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNamespaceResponse.ProtoReflect.Descriptor instead.
func (*CreateNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_namespace_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNamespaceResponse) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

// GetNamespaceRequest retrieves a namespace.
type GetNamespaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace name (empty string = default namespace).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// with_counts asks for the namespace's document counts.
	WithCounts bool `protobuf:"varint,2,opt,name=with_counts,json=withCounts,proto3" json:"with_counts,omitempty"`
	// Organization ID (required, must be valid DNS hostname).
	OrgId         string `protobuf:"bytes,10,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNamespaceRequest) Reset() {
	*x = GetNamespaceRequest{}
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespaceRequest) ProtoMessage() {}

func (x *GetNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespaceRequest.ProtoReflect.Descriptor instead.
func (*GetNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_namespace_proto_rawDescGZIP(), []int{3}
}

func (x *GetNamespaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetNamespaceRequest) GetWithCounts() bool {
	if x != nil {
		return x.WithCounts
	}
	return false
}

func (x *GetNamespaceRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// GetNamespaceResponse carries the namespace.
type GetNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *Namespace             `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNamespaceResponse) Reset() {
	*x = GetNamespaceResponse{}
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespaceResponse) ProtoMessage() {}

func (x *GetNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespaceResponse.ProtoReflect.Descriptor instead.
func (*GetNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_namespace_proto_rawDescGZIP(), []int{4}
}

func (x *GetNamespaceResponse) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

// ListNamespacesRequest lists an organization's namespaces. The default
// namespace is always listed: it exists before anything gives it a record.
type ListNamespacesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// with_counts asks for each namespace's document counts.
	WithCounts bool `protobuf:"varint,1,opt,name=with_counts,json=withCounts,proto3" json:"with_counts,omitempty"`
	// Organization ID (required, must be valid DNS hostname).
	OrgId         string `protobuf:"bytes,10,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesRequest) Reset() {
	*x = ListNamespacesRequest{}
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesRequest) ProtoMessage() {}

func (x *ListNamespacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesRequest.ProtoReflect.Descriptor instead.
func (*ListNamespacesRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_namespace_proto_rawDescGZIP(), []int{5}
}

func (x *ListNamespacesRequest) GetWithCounts() bool {
	if x != nil {
		return x.WithCounts
	}
	return false
}

func (x *ListNamespacesRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// ListNamespacesResponse carries the organization's namespaces, by name.
type ListNamespacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []*Namespace           `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesResponse) Reset() {
	*x = ListNamespacesResponse{}
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesResponse) ProtoMessage() {}

func (x *ListNamespacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesResponse.ProtoReflect.Descriptor instead.
func (*ListNamespacesResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_namespace_proto_rawDescGZIP(), []int{6}
}

func (x *ListNamespacesResponse) GetNamespaces() []*Namespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

// DeleteNamespaceRequest deletes a namespace. The default namespace cannot
// be deleted, nor can one that still holds attestations or policies.
type DeleteNamespaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Organization ID (required, must be valid DNS hostname).
	OrgId         string `protobuf:"bytes,10,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNamespaceRequest) Reset() {
	*x = DeleteNamespaceRequest{}
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNamespaceRequest) ProtoMessage() {}

func (x *DeleteNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNamespaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_namespace_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteNamespaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteNamespaceRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// DeleteNamespaceResponse confirms deletion.
type DeleteNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNamespaceResponse) Reset() {
	*x = DeleteNamespaceResponse{}
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNamespaceResponse) ProtoMessage() {}

func (x *DeleteNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNamespaceResponse.ProtoReflect.Descriptor instead.
func (*DeleteNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_namespace_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteNamespaceResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// SetNamespaceVisibilityRequest opens or closes a namespace to anyone (see
// Namespace.public). Opening the default namespace creates its record.
type SetNamespaceVisibilityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace name (empty string = default namespace).
	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Public bool   `protobuf:"varint,2,opt,name=public,proto3" json:"public,omitempty"`
	// Organization ID (required, must be valid DNS hostname).
	OrgId         string `protobuf:"bytes,10,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNamespaceVisibilityRequest) Reset() {
	*x = SetNamespaceVisibilityRequest{}
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNamespaceVisibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNamespaceVisibilityRequest) ProtoMessage() {}

func (x *SetNamespaceVisibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNamespaceVisibilityRequest.ProtoReflect.Descriptor instead.
func (*SetNamespaceVisibilityRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_namespace_proto_rawDescGZIP(), []int{9}
}

func (x *SetNamespaceVisibilityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetNamespaceVisibilityRequest) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *SetNamespaceVisibilityRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// SetNamespaceVisibilityResponse carries the namespace as stored.
type SetNamespaceVisibilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *Namespace             `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNamespaceVisibilityResponse) Reset() {
	*x = SetNamespaceVisibilityResponse{}
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNamespaceVisibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNamespaceVisibilityResponse) ProtoMessage() {}

func (x *SetNamespaceVisibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_namespace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNamespaceVisibilityResponse.ProtoReflect.Descriptor instead.
func (*SetNamespaceVisibilityResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_namespace_proto_rawDescGZIP(), []int{10}
}

func (x *SetNamespaceVisibilityResponse) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

var File_carabiner_stash_v1_namespace_proto protoreflect.FileDescriptor

const file_carabiner_stash_v1_namespace_proto_rawDesc = "" +
	"\n" +
	"\"carabiner/stash/v1/namespace.proto\x12\x12carabiner.stash.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc5\x02\n" +
	"\tNamespace\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06public\x18\x02 \x01(\bR\x06public\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x120\n" +
	"\x11attestation_count\x18\x05 \x01(\x03H\x00R\x10attestationCount\x88\x01\x01\x12&\n" +
	"\fpolicy_count\x18\x06 \x01(\x03H\x01R\vpolicyCount\x88\x01\x01\x12\x15\n" +
	"\x06org_id\x18\n" +
	" \x01(\tR\x05orgIdB\x14\n" +
	"\x12_attestation_countB\x0f\n" +
	"\r_policy_count\"[\n" +
	"\x16CreateNamespaceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06public\x18\x02 \x01(\bR\x06public\x12\x15\n" +
	"\x06org_id\x18\n" +
	" \x01(\tR\x05orgId\"V\n" +
	"\x17CreateNamespaceResponse\x12;\n" +
	"\tnamespace\x18\x01 \x01(\v2\x1d.carabiner.stash.v1.NamespaceR\tnamespace\"a\n" +
	"\x13GetNamespaceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vwith_counts\x18\x02 \x01(\bR\n" +
	"withCounts\x12\x15\n" +
	"\x06org_id\x18\n" +
	" \x01(\tR\x05orgId\"S\n" +
	"\x14GetNamespaceResponse\x12;\n" +
	"\tnamespace\x18\x01 \x01(\v2\x1d.carabiner.stash.v1.NamespaceR\tnamespace\"O\n" +
	"\x15ListNamespacesRequest\x12\x1f\n" +
	"\vwith_counts\x18\x01 \x01(\bR\n" +
	"withCounts\x12\x15\n" +
	"\x06org_id\x18\n" +
	" \x01(\tR\x05orgId\"W\n" +
	"\x16ListNamespacesResponse\x12=\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\v2\x1d.carabiner.stash.v1.NamespaceR\n" +
	"namespaces\"C\n" +
	"\x16DeleteNamespaceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06org_id\x18\n" +
	" \x01(\tR\x05orgId\"3\n" +
	"\x17DeleteNamespaceResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"b\n" +
	"\x1dSetNamespaceVisibilityRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06public\x18\x02 \x01(\bR\x06public\x12\x15\n" +
	"\x06org_id\x18\n" +
	" \x01(\tR\x05orgId\"]\n" +
	"\x1eSetNamespaceVisibilityResponse\x12;\n" +
	"\tnamespace\x18\x01 \x01(\v2\x1d.carabiner.stash.v1.NamespaceR\tnamespaceB\xcd\x01\n" +
	"\x16com.carabiner.stash.v1B\x0eNamespaceProtoP\x01Z9github.com/carabiner-dev/stash/carabiner/stash/v1;stashv1\xa2\x02\x03CSX\xaa\x02\x12Carabiner.Stash.V1\xca\x02\x12Carabiner\\Stash\\V1\xe2\x02\x1eCarabiner\\Stash\\V1\\GPBMetadata\xea\x02\x14Carabiner::Stash::V1b\x06proto3"

var (
	file_carabiner_stash_v1_namespace_proto_rawDescOnce sync.Once
	file_carabiner_stash_v1_namespace_proto_rawDescData []byte
)

func file_carabiner_stash_v1_namespace_proto_rawDescGZIP() []byte {
	file_carabiner_stash_v1_namespace_proto_rawDescOnce.Do(func() {
		file_carabiner_stash_v1_namespace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carabiner_stash_v1_namespace_proto_rawDesc), len(file_carabiner_stash_v1_namespace_proto_rawDesc)))
	})
	return file_carabiner_stash_v1_namespace_proto_rawDescData
}

var file_carabiner_stash_v1_namespace_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_carabiner_stash_v1_namespace_proto_goTypes = []any{
	(*Namespace)(nil),                      // 0: carabiner.stash.v1.Namespace
	(*CreateNamespaceRequest)(nil),         // 1: carabiner.stash.v1.CreateNamespaceRequest
	(*CreateNamespaceResponse)(nil),        // 2: carabiner.stash.v1.CreateNamespaceResponse
	(*GetNamespaceRequest)(nil),            // 3: carabiner.stash.v1.GetNamespaceRequest
	(*GetNamespaceResponse)(nil),           // 4: carabiner.stash.v1.GetNamespaceResponse
	(*ListNamespacesRequest)(nil),          // 5: carabiner.stash.v1.ListNamespacesRequest
	(*ListNamespacesResponse)(nil),         // 6: carabiner.stash.v1.ListNamespacesResponse
	(*DeleteNamespaceRequest)(nil),         // 7: carabiner.stash.v1.DeleteNamespaceRequest
	(*DeleteNamespaceResponse)(nil),        // 8: carabiner.stash.v1.DeleteNamespaceResponse
	(*SetNamespaceVisibilityRequest)(nil),  // 9: carabiner.stash.v1.SetNamespaceVisibilityRequest
	(*SetNamespaceVisibilityResponse)(nil), // 10: carabiner.stash.v1.SetNamespaceVisibilityResponse
	(*timestamppb.Timestamp)(nil),          // 11: google.protobuf.Timestamp
}
var file_carabiner_stash_v1_namespace_proto_depIdxs = []int32{
	11, // 0: carabiner.stash.v1.Namespace.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: carabiner.stash.v1.Namespace.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: carabiner.stash.v1.CreateNamespaceResponse.namespace:type_name -> carabiner.stash.v1.Namespace
	0,  // 3: carabiner.stash.v1.GetNamespaceResponse.namespace:type_name -> carabiner.stash.v1.Namespace
	0,  // 4: carabiner.stash.v1.ListNamespacesResponse.namespaces:type_name -> carabiner.stash.v1.Namespace
	0,  // 5: carabiner.stash.v1.SetNamespaceVisibilityResponse.namespace:type_name -> carabiner.stash.v1.Namespace
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_carabiner_stash_v1_namespace_proto_init() }
func file_carabiner_stash_v1_namespace_proto_init() {
	if File_carabiner_stash_v1_namespace_proto != nil {
		return
	}
	file_carabiner_stash_v1_namespace_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carabiner_stash_v1_namespace_proto_rawDesc), len(file_carabiner_stash_v1_namespace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_carabiner_stash_v1_namespace_proto_goTypes,
		DependencyIndexes: file_carabiner_stash_v1_namespace_proto_depIdxs,
		MessageInfos:      file_carabiner_stash_v1_namespace_proto_msgTypes,
	}.Build()
	File_carabiner_stash_v1_namespace_proto = out.File
	file_carabiner_stash_v1_namespace_proto_goTypes = nil
	file_carabiner_stash_v1_namespace_proto_depIdxs = nil
}
