// SPDX-FileCopyrightText: Copyright 2026 Carabiner Systems, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: carabiner/stash/v1/policy.proto

package stashv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Policy is one version of a policy lineage. A lineage — keyed by
// (org, namespace, lineage_id) — is an append-only sequence of ampel policy
// documents; version orders its members and is 0-based (the first is version 0).
type Policy struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LineageId        string                 `protobuf:"bytes,1,opt,name=lineage_id,json=lineageId,proto3" json:"lineage_id,omitempty"`
	Version          int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	DocumentKind     string                 `protobuf:"bytes,3,opt,name=document_kind,json=documentKind,proto3" json:"document_kind,omitempty"` // policy | policyset | policygroup
	ContentHash      string                 `protobuf:"bytes,4,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	PredicateType    string                 `protobuf:"bytes,5,opt,name=predicate_type,json=predicateType,proto3" json:"predicate_type,omitempty"`
	Signed           bool                   `protobuf:"varint,6,opt,name=signed,proto3" json:"signed,omitempty"`
	Validated        bool                   `protobuf:"varint,7,opt,name=validated,proto3" json:"validated,omitempty"`
	ValidationError  string                 `protobuf:"bytes,8,opt,name=validation_error,json=validationError,proto3" json:"validation_error,omitempty"`
	SignerIdentities []string               `protobuf:"bytes,9,rep,name=signer_identities,json=signerIdentities,proto3" json:"signer_identities,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_carabiner_stash_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *Policy) GetLineageId() string {
	if x != nil {
		return x.LineageId
	}
	return ""
}

func (x *Policy) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Policy) GetDocumentKind() string {
	if x != nil {
		return x.DocumentKind
	}
	return ""
}

func (x *Policy) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *Policy) GetPredicateType() string {
	if x != nil {
		return x.PredicateType
	}
	return ""
}

func (x *Policy) GetSigned() bool {
	if x != nil {
		return x.Signed
	}
	return false
}

func (x *Policy) GetValidated() bool {
	if x != nil {
		return x.Validated
	}
	return false
}

func (x *Policy) GetValidationError() string {
	if x != nil {
		return x.ValidationError
	}
	return ""
}

func (x *Policy) GetSignerIdentities() []string {
	if x != nil {
		return x.SignerIdentities
	}
	return nil
}

func (x *Policy) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// PolicyResult is the outcome of storing one policy document.
type PolicyResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LineageId        string                 `protobuf:"bytes,1,opt,name=lineage_id,json=lineageId,proto3" json:"lineage_id,omitempty"`
	Version          int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	DocumentKind     string                 `protobuf:"bytes,3,opt,name=document_kind,json=documentKind,proto3" json:"document_kind,omitempty"`
	ContentHash      string                 `protobuf:"bytes,4,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Signed           bool                   `protobuf:"varint,5,opt,name=signed,proto3" json:"signed,omitempty"`
	Validated        bool                   `protobuf:"varint,6,opt,name=validated,proto3" json:"validated,omitempty"`
	SignerIdentities []string               `protobuf:"bytes,7,rep,name=signer_identities,json=signerIdentities,proto3" json:"signer_identities,omitempty"`
	// existed is true when the exact document was already the lineage head, so the
	// upload was an idempotent no-op rather than a new version.
	Existed       bool   `protobuf:"varint,8,opt,name=existed,proto3" json:"existed,omitempty"`
	Error         string `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"` // set when this document was rejected
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyResult) Reset() {
	*x = PolicyResult{}
	mi := &file_carabiner_stash_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyResult) ProtoMessage() {}

func (x *PolicyResult) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyResult.ProtoReflect.Descriptor instead.
func (*PolicyResult) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyResult) GetLineageId() string {
	if x != nil {
		return x.LineageId
	}
	return ""
}

func (x *PolicyResult) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicyResult) GetDocumentKind() string {
	if x != nil {
		return x.DocumentKind
	}
	return ""
}

func (x *PolicyResult) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *PolicyResult) GetSigned() bool {
	if x != nil {
		return x.Signed
	}
	return false
}

func (x *PolicyResult) GetValidated() bool {
	if x != nil {
		return x.Validated
	}
	return false
}

func (x *PolicyResult) GetSignerIdentities() []string {
	if x != nil {
		return x.SignerIdentities
	}
	return nil
}

func (x *PolicyResult) GetExisted() bool {
	if x != nil {
		return x.Existed
	}
	return false
}

func (x *PolicyResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_carabiner_stash_v1_policy_proto protoreflect.FileDescriptor

const file_carabiner_stash_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x1fcarabiner/stash/v1/policy.proto\x12\x12carabiner.stash.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x02\n" +
	"\x06Policy\x12\x1d\n" +
	"\n" +
	"lineage_id\x18\x01 \x01(\tR\tlineageId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12#\n" +
	"\rdocument_kind\x18\x03 \x01(\tR\fdocumentKind\x12!\n" +
	"\fcontent_hash\x18\x04 \x01(\tR\vcontentHash\x12%\n" +
	"\x0epredicate_type\x18\x05 \x01(\tR\rpredicateType\x12\x16\n" +
	"\x06signed\x18\x06 \x01(\bR\x06signed\x12\x1c\n" +
	"\tvalidated\x18\a \x01(\bR\tvalidated\x12)\n" +
	"\x10validation_error\x18\b \x01(\tR\x0fvalidationError\x12+\n" +
	"\x11signer_identities\x18\t \x03(\tR\x10signerIdentities\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa2\x02\n" +
	"\fPolicyResult\x12\x1d\n" +
	"\n" +
	"lineage_id\x18\x01 \x01(\tR\tlineageId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12#\n" +
	"\rdocument_kind\x18\x03 \x01(\tR\fdocumentKind\x12!\n" +
	"\fcontent_hash\x18\x04 \x01(\tR\vcontentHash\x12\x16\n" +
	"\x06signed\x18\x05 \x01(\bR\x06signed\x12\x1c\n" +
	"\tvalidated\x18\x06 \x01(\bR\tvalidated\x12+\n" +
	"\x11signer_identities\x18\a \x03(\tR\x10signerIdentities\x12\x18\n" +
	"\aexisted\x18\b \x01(\bR\aexisted\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05errorB\xca\x01\n" +
	"\x16com.carabiner.stash.v1B\vPolicyProtoP\x01Z9github.com/carabiner-dev/stash/carabiner/stash/v1;stashv1\xa2\x02\x03CSX\xaa\x02\x12Carabiner.Stash.V1\xca\x02\x12Carabiner\\Stash\\V1\xe2\x02\x1eCarabiner\\Stash\\V1\\GPBMetadata\xea\x02\x14Carabiner::Stash::V1b\x06proto3"

var (
	file_carabiner_stash_v1_policy_proto_rawDescOnce sync.Once
	file_carabiner_stash_v1_policy_proto_rawDescData []byte
)

func file_carabiner_stash_v1_policy_proto_rawDescGZIP() []byte {
	file_carabiner_stash_v1_policy_proto_rawDescOnce.Do(func() {
		file_carabiner_stash_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carabiner_stash_v1_policy_proto_rawDesc), len(file_carabiner_stash_v1_policy_proto_rawDesc)))
	})
	return file_carabiner_stash_v1_policy_proto_rawDescData
}

var file_carabiner_stash_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_carabiner_stash_v1_policy_proto_goTypes = []any{
	(*Policy)(nil),                // 0: carabiner.stash.v1.Policy
	(*PolicyResult)(nil),          // 1: carabiner.stash.v1.PolicyResult
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_carabiner_stash_v1_policy_proto_depIdxs = []int32{
	2, // 0: carabiner.stash.v1.Policy.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_carabiner_stash_v1_policy_proto_init() }
func file_carabiner_stash_v1_policy_proto_init() {
	if File_carabiner_stash_v1_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carabiner_stash_v1_policy_proto_rawDesc), len(file_carabiner_stash_v1_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_carabiner_stash_v1_policy_proto_goTypes,
		DependencyIndexes: file_carabiner_stash_v1_policy_proto_depIdxs,
		MessageInfos:      file_carabiner_stash_v1_policy_proto_msgTypes,
	}.Build()
	File_carabiner_stash_v1_policy_proto = out.File
	file_carabiner_stash_v1_policy_proto_goTypes = nil
	file_carabiner_stash_v1_policy_proto_depIdxs = nil
}
