// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: carabiner/stash/v1/publickey.proto

package stashv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublicKey represents a public key for signature validation.
type PublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	KeyData       []byte                 `protobuf:"bytes,2,opt,name=key_data,json=keyData,proto3" json:"key_data,omitempty"` // PEM-encoded public key
	Algorithm     string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_carabiner_stash_v1_publickey_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_publickey_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_publickey_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKey) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *PublicKey) GetKeyData() []byte {
	if x != nil {
		return x.KeyData
	}
	return nil
}

func (x *PublicKey) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *PublicKey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// UploadPublicKeyRequest uploads a public key.
type UploadPublicKeyRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	KeyData []byte                 `protobuf:"bytes,1,opt,name=key_data,json=keyData,proto3" json:"key_data,omitempty"` // PEM-encoded public key
	// Organization ID (required, must be valid DNS hostname).
	OrgId         string `protobuf:"bytes,10,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPublicKeyRequest) Reset() {
	*x = UploadPublicKeyRequest{}
	mi := &file_carabiner_stash_v1_publickey_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPublicKeyRequest) ProtoMessage() {}

func (x *UploadPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_publickey_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*UploadPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_publickey_proto_rawDescGZIP(), []int{1}
}

func (x *UploadPublicKeyRequest) GetKeyData() []byte {
	if x != nil {
		return x.KeyData
	}
	return nil
}

func (x *UploadPublicKeyRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// UploadPublicKeyResponse returns the key ID.
type UploadPublicKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPublicKeyResponse) Reset() {
	*x = UploadPublicKeyResponse{}
	mi := &file_carabiner_stash_v1_publickey_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPublicKeyResponse) ProtoMessage() {}

func (x *UploadPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_publickey_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*UploadPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_publickey_proto_rawDescGZIP(), []int{2}
}

func (x *UploadPublicKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// DeletePublicKeyRequest deletes a public key.
type DeletePublicKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	KeyId string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// Organization ID (required, must be valid DNS hostname).
	OrgId         string `protobuf:"bytes,10,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePublicKeyRequest) Reset() {
	*x = DeletePublicKeyRequest{}
	mi := &file_carabiner_stash_v1_publickey_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePublicKeyRequest) ProtoMessage() {}

func (x *DeletePublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_publickey_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePublicKeyRequest.ProtoReflect.Descriptor instead.
func (*DeletePublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_publickey_proto_rawDescGZIP(), []int{3}
}

func (x *DeletePublicKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *DeletePublicKeyRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// DeletePublicKeyResponse confirms deletion.
type DeletePublicKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePublicKeyResponse) Reset() {
	*x = DeletePublicKeyResponse{}
	mi := &file_carabiner_stash_v1_publickey_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePublicKeyResponse) ProtoMessage() {}

func (x *DeletePublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_publickey_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePublicKeyResponse.ProtoReflect.Descriptor instead.
func (*DeletePublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_publickey_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePublicKeyResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// ListPublicKeysRequest lists public keys.
type ListPublicKeysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Organization ID (required, must be valid DNS hostname).
	OrgId         string `protobuf:"bytes,10,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublicKeysRequest) Reset() {
	*x = ListPublicKeysRequest{}
	mi := &file_carabiner_stash_v1_publickey_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublicKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicKeysRequest) ProtoMessage() {}

func (x *ListPublicKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_publickey_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicKeysRequest.ProtoReflect.Descriptor instead.
func (*ListPublicKeysRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_publickey_proto_rawDescGZIP(), []int{5}
}

func (x *ListPublicKeysRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// ListPublicKeysResponse contains public keys.
type ListPublicKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*PublicKey           `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublicKeysResponse) Reset() {
	*x = ListPublicKeysResponse{}
	mi := &file_carabiner_stash_v1_publickey_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublicKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicKeysResponse) ProtoMessage() {}

func (x *ListPublicKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_publickey_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicKeysResponse.ProtoReflect.Descriptor instead.
func (*ListPublicKeysResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_publickey_proto_rawDescGZIP(), []int{6}
}

func (x *ListPublicKeysResponse) GetKeys() []*PublicKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_carabiner_stash_v1_publickey_proto protoreflect.FileDescriptor

const file_carabiner_stash_v1_publickey_proto_rawDesc = "" +
	"\n" +
	"\"carabiner/stash/v1/publickey.proto\x12\x12carabiner.stash.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x01\n" +
	"\tPublicKey\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x19\n" +
	"\bkey_data\x18\x02 \x01(\fR\akeyData\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"J\n" +
	"\x16UploadPublicKeyRequest\x12\x19\n" +
	"\bkey_data\x18\x01 \x01(\fR\akeyData\x12\x15\n" +
	"\x06org_id\x18\n" +
	" \x01(\tR\x05orgId\"0\n" +
	"\x17UploadPublicKeyResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\"F\n" +
	"\x16DeletePublicKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x15\n" +
	"\x06org_id\x18\n" +
	" \x01(\tR\x05orgId\"3\n" +
	"\x17DeletePublicKeyResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\".\n" +
	"\x15ListPublicKeysRequest\x12\x15\n" +
	"\x06org_id\x18\n" +
	" \x01(\tR\x05orgId\"K\n" +
	"\x16ListPublicKeysResponse\x121\n" +
	"\x04keys\x18\x01 \x03(\v2\x1d.carabiner.stash.v1.PublicKeyR\x04keysB\xcd\x01\n" +
	"\x16com.carabiner.stash.v1B\x0ePublickeyProtoP\x01Z9github.com/carabiner-dev/stash/carabiner/stash/v1;stashv1\xa2\x02\x03CSX\xaa\x02\x12Carabiner.Stash.V1\xca\x02\x12Carabiner\\Stash\\V1\xe2\x02\x1eCarabiner\\Stash\\V1\\GPBMetadata\xea\x02\x14Carabiner::Stash::V1b\x06proto3"

var (
	file_carabiner_stash_v1_publickey_proto_rawDescOnce sync.Once
	file_carabiner_stash_v1_publickey_proto_rawDescData []byte
)

func file_carabiner_stash_v1_publickey_proto_rawDescGZIP() []byte {
	file_carabiner_stash_v1_publickey_proto_rawDescOnce.Do(func() {
		file_carabiner_stash_v1_publickey_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carabiner_stash_v1_publickey_proto_rawDesc), len(file_carabiner_stash_v1_publickey_proto_rawDesc)))
	})
	return file_carabiner_stash_v1_publickey_proto_rawDescData
}

var file_carabiner_stash_v1_publickey_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_carabiner_stash_v1_publickey_proto_goTypes = []any{
	(*PublicKey)(nil),               // 0: carabiner.stash.v1.PublicKey
	(*UploadPublicKeyRequest)(nil),  // 1: carabiner.stash.v1.UploadPublicKeyRequest
	(*UploadPublicKeyResponse)(nil), // 2: carabiner.stash.v1.UploadPublicKeyResponse
	(*DeletePublicKeyRequest)(nil),  // 3: carabiner.stash.v1.DeletePublicKeyRequest
	(*DeletePublicKeyResponse)(nil), // 4: carabiner.stash.v1.DeletePublicKeyResponse
	(*ListPublicKeysRequest)(nil),   // 5: carabiner.stash.v1.ListPublicKeysRequest
	(*ListPublicKeysResponse)(nil),  // 6: carabiner.stash.v1.ListPublicKeysResponse
	(*timestamppb.Timestamp)(nil),   // 7: google.protobuf.Timestamp
}
var file_carabiner_stash_v1_publickey_proto_depIdxs = []int32{
	7, // 0: carabiner.stash.v1.PublicKey.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: carabiner.stash.v1.ListPublicKeysResponse.keys:type_name -> carabiner.stash.v1.PublicKey
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_carabiner_stash_v1_publickey_proto_init() }
func file_carabiner_stash_v1_publickey_proto_init() {
	if File_carabiner_stash_v1_publickey_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carabiner_stash_v1_publickey_proto_rawDesc), len(file_carabiner_stash_v1_publickey_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_carabiner_stash_v1_publickey_proto_goTypes,
		DependencyIndexes: file_carabiner_stash_v1_publickey_proto_depIdxs,
		MessageInfos:      file_carabiner_stash_v1_publickey_proto_msgTypes,
	}.Build()
	File_carabiner_stash_v1_publickey_proto = out.File
	file_carabiner_stash_v1_publickey_proto_goTypes = nil
	file_carabiner_stash_v1_publickey_proto_depIdxs = nil
}
