// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: carabiner/stash/v1/stash.proto

package stashv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StashService_UploadAttestations_FullMethodName = "/carabiner.stash.v1.StashService/UploadAttestations"
	StashService_GetAttestation_FullMethodName     = "/carabiner.stash.v1.StashService/GetAttestation"
	StashService_ListAttestations_FullMethodName   = "/carabiner.stash.v1.StashService/ListAttestations"
	StashService_DeleteAttestation_FullMethodName  = "/carabiner.stash.v1.StashService/DeleteAttestation"
	StashService_UpdateAttestation_FullMethodName  = "/carabiner.stash.v1.StashService/UpdateAttestation"
	StashService_UploadPublicKey_FullMethodName    = "/carabiner.stash.v1.StashService/UploadPublicKey"
	StashService_DeletePublicKey_FullMethodName    = "/carabiner.stash.v1.StashService/DeletePublicKey"
	StashService_ListPublicKeys_FullMethodName     = "/carabiner.stash.v1.StashService/ListPublicKeys"
	StashService_HealthCheck_FullMethodName        = "/carabiner.stash.v1.StashService/HealthCheck"
)

// StashServiceClient is the client API for StashService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StashService provides attestation storage and retrieval operations.
type StashServiceClient interface {
	// UploadAttestations stores one or more attestations.
	UploadAttestations(ctx context.Context, in *UploadAttestationsRequest, opts ...grpc.CallOption) (*UploadAttestationsResponse, error)
	// GetAttestation retrieves an attestation by ID or hash.
	GetAttestation(ctx context.Context, in *GetAttestationRequest, opts ...grpc.CallOption) (*GetAttestationResponse, error)
	// ListAttestations queries attestations with filters and pagination.
	ListAttestations(ctx context.Context, in *ListAttestationsRequest, opts ...grpc.CallOption) (*ListAttestationsResponse, error)
	// DeleteAttestation removes an attestation.
	DeleteAttestation(ctx context.Context, in *DeleteAttestationRequest, opts ...grpc.CallOption) (*DeleteAttestationResponse, error)
	// UpdateAttestation updates attestation metadata (currently not implemented).
	UpdateAttestation(ctx context.Context, in *UpdateAttestationRequest, opts ...grpc.CallOption) (*UpdateAttestationResponse, error)
	// UploadPublicKey stores a public key for signature validation.
	UploadPublicKey(ctx context.Context, in *UploadPublicKeyRequest, opts ...grpc.CallOption) (*UploadPublicKeyResponse, error)
	// DeletePublicKey removes a public key.
	DeletePublicKey(ctx context.Context, in *DeletePublicKeyRequest, opts ...grpc.CallOption) (*DeletePublicKeyResponse, error)
	// ListPublicKeys retrieves all public keys for an organization.
	ListPublicKeys(ctx context.Context, in *ListPublicKeysRequest, opts ...grpc.CallOption) (*ListPublicKeysResponse, error)
	// HealthCheck checks service health.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type stashServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStashServiceClient(cc grpc.ClientConnInterface) StashServiceClient {
	return &stashServiceClient{cc}
}

func (c *stashServiceClient) UploadAttestations(ctx context.Context, in *UploadAttestationsRequest, opts ...grpc.CallOption) (*UploadAttestationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadAttestationsResponse)
	err := c.cc.Invoke(ctx, StashService_UploadAttestations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stashServiceClient) GetAttestation(ctx context.Context, in *GetAttestationRequest, opts ...grpc.CallOption) (*GetAttestationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttestationResponse)
	err := c.cc.Invoke(ctx, StashService_GetAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stashServiceClient) ListAttestations(ctx context.Context, in *ListAttestationsRequest, opts ...grpc.CallOption) (*ListAttestationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAttestationsResponse)
	err := c.cc.Invoke(ctx, StashService_ListAttestations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stashServiceClient) DeleteAttestation(ctx context.Context, in *DeleteAttestationRequest, opts ...grpc.CallOption) (*DeleteAttestationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAttestationResponse)
	err := c.cc.Invoke(ctx, StashService_DeleteAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stashServiceClient) UpdateAttestation(ctx context.Context, in *UpdateAttestationRequest, opts ...grpc.CallOption) (*UpdateAttestationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAttestationResponse)
	err := c.cc.Invoke(ctx, StashService_UpdateAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stashServiceClient) UploadPublicKey(ctx context.Context, in *UploadPublicKeyRequest, opts ...grpc.CallOption) (*UploadPublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadPublicKeyResponse)
	err := c.cc.Invoke(ctx, StashService_UploadPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stashServiceClient) DeletePublicKey(ctx context.Context, in *DeletePublicKeyRequest, opts ...grpc.CallOption) (*DeletePublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePublicKeyResponse)
	err := c.cc.Invoke(ctx, StashService_DeletePublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stashServiceClient) ListPublicKeys(ctx context.Context, in *ListPublicKeysRequest, opts ...grpc.CallOption) (*ListPublicKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPublicKeysResponse)
	err := c.cc.Invoke(ctx, StashService_ListPublicKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stashServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, StashService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StashServiceServer is the server API for StashService service.
// All implementations must embed UnimplementedStashServiceServer
// for forward compatibility.
//
// StashService provides attestation storage and retrieval operations.
type StashServiceServer interface {
	// UploadAttestations stores one or more attestations.
	UploadAttestations(context.Context, *UploadAttestationsRequest) (*UploadAttestationsResponse, error)
	// GetAttestation retrieves an attestation by ID or hash.
	GetAttestation(context.Context, *GetAttestationRequest) (*GetAttestationResponse, error)
	// ListAttestations queries attestations with filters and pagination.
	ListAttestations(context.Context, *ListAttestationsRequest) (*ListAttestationsResponse, error)
	// DeleteAttestation removes an attestation.
	DeleteAttestation(context.Context, *DeleteAttestationRequest) (*DeleteAttestationResponse, error)
	// UpdateAttestation updates attestation metadata (currently not implemented).
	UpdateAttestation(context.Context, *UpdateAttestationRequest) (*UpdateAttestationResponse, error)
	// UploadPublicKey stores a public key for signature validation.
	UploadPublicKey(context.Context, *UploadPublicKeyRequest) (*UploadPublicKeyResponse, error)
	// DeletePublicKey removes a public key.
	DeletePublicKey(context.Context, *DeletePublicKeyRequest) (*DeletePublicKeyResponse, error)
	// ListPublicKeys retrieves all public keys for an organization.
	ListPublicKeys(context.Context, *ListPublicKeysRequest) (*ListPublicKeysResponse, error)
	// HealthCheck checks service health.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedStashServiceServer()
}

// UnimplementedStashServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStashServiceServer struct{}

func (UnimplementedStashServiceServer) UploadAttestations(context.Context, *UploadAttestationsRequest) (*UploadAttestationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadAttestations not implemented")
}
func (UnimplementedStashServiceServer) GetAttestation(context.Context, *GetAttestationRequest) (*GetAttestationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAttestation not implemented")
}
func (UnimplementedStashServiceServer) ListAttestations(context.Context, *ListAttestationsRequest) (*ListAttestationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAttestations not implemented")
}
func (UnimplementedStashServiceServer) DeleteAttestation(context.Context, *DeleteAttestationRequest) (*DeleteAttestationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAttestation not implemented")
}
func (UnimplementedStashServiceServer) UpdateAttestation(context.Context, *UpdateAttestationRequest) (*UpdateAttestationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAttestation not implemented")
}
func (UnimplementedStashServiceServer) UploadPublicKey(context.Context, *UploadPublicKeyRequest) (*UploadPublicKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadPublicKey not implemented")
}
func (UnimplementedStashServiceServer) DeletePublicKey(context.Context, *DeletePublicKeyRequest) (*DeletePublicKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePublicKey not implemented")
}
func (UnimplementedStashServiceServer) ListPublicKeys(context.Context, *ListPublicKeysRequest) (*ListPublicKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPublicKeys not implemented")
}
func (UnimplementedStashServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedStashServiceServer) mustEmbedUnimplementedStashServiceServer() {}
func (UnimplementedStashServiceServer) testEmbeddedByValue()                      {}

// UnsafeStashServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StashServiceServer will
// result in compilation errors.
type UnsafeStashServiceServer interface {
	mustEmbedUnimplementedStashServiceServer()
}

func RegisterStashServiceServer(s grpc.ServiceRegistrar, srv StashServiceServer) {
	// If the following call panics, it indicates UnimplementedStashServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StashService_ServiceDesc, srv)
}

func _StashService_UploadAttestations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadAttestationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StashServiceServer).UploadAttestations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StashService_UploadAttestations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StashServiceServer).UploadAttestations(ctx, req.(*UploadAttestationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StashService_GetAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttestationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StashServiceServer).GetAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StashService_GetAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StashServiceServer).GetAttestation(ctx, req.(*GetAttestationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StashService_ListAttestations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAttestationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StashServiceServer).ListAttestations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StashService_ListAttestations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StashServiceServer).ListAttestations(ctx, req.(*ListAttestationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StashService_DeleteAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAttestationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StashServiceServer).DeleteAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StashService_DeleteAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StashServiceServer).DeleteAttestation(ctx, req.(*DeleteAttestationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StashService_UpdateAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAttestationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StashServiceServer).UpdateAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StashService_UpdateAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StashServiceServer).UpdateAttestation(ctx, req.(*UpdateAttestationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StashService_UploadPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StashServiceServer).UploadPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StashService_UploadPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StashServiceServer).UploadPublicKey(ctx, req.(*UploadPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StashService_DeletePublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StashServiceServer).DeletePublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StashService_DeletePublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StashServiceServer).DeletePublicKey(ctx, req.(*DeletePublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StashService_ListPublicKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublicKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StashServiceServer).ListPublicKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StashService_ListPublicKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StashServiceServer).ListPublicKeys(ctx, req.(*ListPublicKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StashService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StashServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StashService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StashServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StashService_ServiceDesc is the grpc.ServiceDesc for StashService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StashService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "carabiner.stash.v1.StashService",
	HandlerType: (*StashServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadAttestations",
			Handler:    _StashService_UploadAttestations_Handler,
		},
		{
			MethodName: "GetAttestation",
			Handler:    _StashService_GetAttestation_Handler,
		},
		{
			MethodName: "ListAttestations",
			Handler:    _StashService_ListAttestations_Handler,
		},
		{
			MethodName: "DeleteAttestation",
			Handler:    _StashService_DeleteAttestation_Handler,
		},
		{
			MethodName: "UpdateAttestation",
			Handler:    _StashService_UpdateAttestation_Handler,
		},
		{
			MethodName: "UploadPublicKey",
			Handler:    _StashService_UploadPublicKey_Handler,
		},
		{
			MethodName: "DeletePublicKey",
			Handler:    _StashService_DeletePublicKey_Handler,
		},
		{
			MethodName: "ListPublicKeys",
			Handler:    _StashService_ListPublicKeys_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _StashService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "carabiner/stash/v1/stash.proto",
}
