// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: carabiner/stash/v1/stash.proto

package stashv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UploadAttestationsRequest contains attestations to upload.
type UploadAttestationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Namespace for the attestations (empty string = default namespace).
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Raw attestation JSON (max 1MB each, max 100 attestations).
	Attestations [][]byte `protobuf:"bytes,2,rep,name=attestations,proto3" json:"attestations,omitempty"`
	// Organization ID (required, must be valid DNS hostname).
	OrgId         string `protobuf:"bytes,10,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAttestationsRequest) Reset() {
	*x = UploadAttestationsRequest{}
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAttestationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAttestationsRequest) ProtoMessage() {}

func (x *UploadAttestationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAttestationsRequest.ProtoReflect.Descriptor instead.
func (*UploadAttestationsRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_stash_proto_rawDescGZIP(), []int{0}
}

func (x *UploadAttestationsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UploadAttestationsRequest) GetAttestations() [][]byte {
	if x != nil {
		return x.Attestations
	}
	return nil
}

func (x *UploadAttestationsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// UploadAttestationsResponse contains upload results.
type UploadAttestationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*AttestationResult   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAttestationsResponse) Reset() {
	*x = UploadAttestationsResponse{}
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAttestationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAttestationsResponse) ProtoMessage() {}

func (x *UploadAttestationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAttestationsResponse.ProtoReflect.Descriptor instead.
func (*UploadAttestationsResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_stash_proto_rawDescGZIP(), []int{1}
}

func (x *UploadAttestationsResponse) GetResults() []*AttestationResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// AttestationResult represents the result of uploading a single attestation.
type AttestationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttestationId string                 `protobuf:"bytes,1,opt,name=attestation_id,json=attestationId,proto3" json:"attestation_id,omitempty"`
	ContentHash   string                 `protobuf:"bytes,2,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Stored        bool                   `protobuf:"varint,3,opt,name=stored,proto3" json:"stored,omitempty"`
	Validated     bool                   `protobuf:"varint,4,opt,name=validated,proto3" json:"validated,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`      // Error message if storage or validation failed
	Existed       bool                   `protobuf:"varint,6,opt,name=existed,proto3" json:"existed,omitempty"` // True when an identical attestation was already stored (idempotent upload)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestationResult) Reset() {
	*x = AttestationResult{}
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationResult) ProtoMessage() {}

func (x *AttestationResult) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationResult.ProtoReflect.Descriptor instead.
func (*AttestationResult) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_stash_proto_rawDescGZIP(), []int{2}
}

func (x *AttestationResult) GetAttestationId() string {
	if x != nil {
		return x.AttestationId
	}
	return ""
}

func (x *AttestationResult) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *AttestationResult) GetStored() bool {
	if x != nil {
		return x.Stored
	}
	return false
}

func (x *AttestationResult) GetValidated() bool {
	if x != nil {
		return x.Validated
	}
	return false
}

func (x *AttestationResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AttestationResult) GetExisted() bool {
	if x != nil {
		return x.Existed
	}
	return false
}

// GetAttestationRequest retrieves an attestation.
type GetAttestationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Namespace (empty string = default namespace).
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetAttestationRequest_AttestationId
	//	*GetAttestationRequest_ContentHash
	//	*GetAttestationRequest_PredicateHash
	Identifier isGetAttestationRequest_Identifier `protobuf_oneof:"identifier"`
	// If true, only return raw attestation
	RawOnly bool `protobuf:"varint,5,opt,name=raw_only,json=rawOnly,proto3" json:"raw_only,omitempty"`
	// If true, only return predicate
	PredicateOnly bool `protobuf:"varint,6,opt,name=predicate_only,json=predicateOnly,proto3" json:"predicate_only,omitempty"`
	// Organization ID (required, must be valid DNS hostname).
	OrgId         string `protobuf:"bytes,10,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttestationRequest) Reset() {
	*x = GetAttestationRequest{}
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttestationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttestationRequest) ProtoMessage() {}

func (x *GetAttestationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttestationRequest.ProtoReflect.Descriptor instead.
func (*GetAttestationRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_stash_proto_rawDescGZIP(), []int{3}
}

func (x *GetAttestationRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetAttestationRequest) GetIdentifier() isGetAttestationRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetAttestationRequest) GetAttestationId() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetAttestationRequest_AttestationId); ok {
			return x.AttestationId
		}
	}
	return ""
}

func (x *GetAttestationRequest) GetContentHash() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetAttestationRequest_ContentHash); ok {
			return x.ContentHash
		}
	}
	return ""
}

func (x *GetAttestationRequest) GetPredicateHash() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetAttestationRequest_PredicateHash); ok {
			return x.PredicateHash
		}
	}
	return ""
}

func (x *GetAttestationRequest) GetRawOnly() bool {
	if x != nil {
		return x.RawOnly
	}
	return false
}

func (x *GetAttestationRequest) GetPredicateOnly() bool {
	if x != nil {
		return x.PredicateOnly
	}
	return false
}

func (x *GetAttestationRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type isGetAttestationRequest_Identifier interface {
	isGetAttestationRequest_Identifier()
}

type GetAttestationRequest_AttestationId struct {
	AttestationId string `protobuf:"bytes,2,opt,name=attestation_id,json=attestationId,proto3,oneof"`
}

type GetAttestationRequest_ContentHash struct {
	ContentHash string `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3,oneof"`
}

type GetAttestationRequest_PredicateHash struct {
	PredicateHash string `protobuf:"bytes,4,opt,name=predicate_hash,json=predicateHash,proto3,oneof"`
}

func (*GetAttestationRequest_AttestationId) isGetAttestationRequest_Identifier() {}

func (*GetAttestationRequest_ContentHash) isGetAttestationRequest_Identifier() {}

func (*GetAttestationRequest_PredicateHash) isGetAttestationRequest_Identifier() {}

// GetAttestationResponse contains attestation data.
type GetAttestationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Attestation    *Attestation           `protobuf:"bytes,1,opt,name=attestation,proto3" json:"attestation,omitempty"`
	RawAttestation []byte                 `protobuf:"bytes,2,opt,name=raw_attestation,json=rawAttestation,proto3" json:"raw_attestation,omitempty"`
	RawPredicate   []byte                 `protobuf:"bytes,3,opt,name=raw_predicate,json=rawPredicate,proto3" json:"raw_predicate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAttestationResponse) Reset() {
	*x = GetAttestationResponse{}
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttestationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttestationResponse) ProtoMessage() {}

func (x *GetAttestationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttestationResponse.ProtoReflect.Descriptor instead.
func (*GetAttestationResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_stash_proto_rawDescGZIP(), []int{4}
}

func (x *GetAttestationResponse) GetAttestation() *Attestation {
	if x != nil {
		return x.Attestation
	}
	return nil
}

func (x *GetAttestationResponse) GetRawAttestation() []byte {
	if x != nil {
		return x.RawAttestation
	}
	return nil
}

func (x *GetAttestationResponse) GetRawPredicate() []byte {
	if x != nil {
		return x.RawPredicate
	}
	return nil
}

// ListAttestationsRequest queries attestations.
type ListAttestationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Namespace (empty string = default namespace).
	Namespace string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Filters   *Filters `protobuf:"bytes,2,opt,name=filters,proto3" json:"filters,omitempty"`
	Cursor    *Cursor  `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// Organization ID (required, must be valid DNS hostname).
	OrgId         string `protobuf:"bytes,10,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttestationsRequest) Reset() {
	*x = ListAttestationsRequest{}
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttestationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttestationsRequest) ProtoMessage() {}

func (x *ListAttestationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttestationsRequest.ProtoReflect.Descriptor instead.
func (*ListAttestationsRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_stash_proto_rawDescGZIP(), []int{5}
}

func (x *ListAttestationsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListAttestationsRequest) GetFilters() *Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ListAttestationsRequest) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *ListAttestationsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// ListAttestationsResponse contains paginated attestation list.
type ListAttestationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attestations  []*Attestation         `protobuf:"bytes,1,rep,name=attestations,proto3" json:"attestations,omitempty"`
	NextCursor    *Cursor                `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttestationsResponse) Reset() {
	*x = ListAttestationsResponse{}
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttestationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttestationsResponse) ProtoMessage() {}

func (x *ListAttestationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttestationsResponse.ProtoReflect.Descriptor instead.
func (*ListAttestationsResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_stash_proto_rawDescGZIP(), []int{6}
}

func (x *ListAttestationsResponse) GetAttestations() []*Attestation {
	if x != nil {
		return x.Attestations
	}
	return nil
}

func (x *ListAttestationsResponse) GetNextCursor() *Cursor {
	if x != nil {
		return x.NextCursor
	}
	return nil
}

// DeleteAttestationRequest deletes an attestation.
type DeleteAttestationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Namespace (empty string = default namespace).
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*DeleteAttestationRequest_AttestationId
	//	*DeleteAttestationRequest_ContentHash
	Identifier isDeleteAttestationRequest_Identifier `protobuf_oneof:"identifier"`
	// Organization ID (required, must be valid DNS hostname).
	OrgId         string `protobuf:"bytes,10,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttestationRequest) Reset() {
	*x = DeleteAttestationRequest{}
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttestationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttestationRequest) ProtoMessage() {}

func (x *DeleteAttestationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttestationRequest.ProtoReflect.Descriptor instead.
func (*DeleteAttestationRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_stash_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAttestationRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteAttestationRequest) GetIdentifier() isDeleteAttestationRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *DeleteAttestationRequest) GetAttestationId() string {
	if x != nil {
		if x, ok := x.Identifier.(*DeleteAttestationRequest_AttestationId); ok {
			return x.AttestationId
		}
	}
	return ""
}

func (x *DeleteAttestationRequest) GetContentHash() string {
	if x != nil {
		if x, ok := x.Identifier.(*DeleteAttestationRequest_ContentHash); ok {
			return x.ContentHash
		}
	}
	return ""
}

func (x *DeleteAttestationRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type isDeleteAttestationRequest_Identifier interface {
	isDeleteAttestationRequest_Identifier()
}

type DeleteAttestationRequest_AttestationId struct {
	AttestationId string `protobuf:"bytes,2,opt,name=attestation_id,json=attestationId,proto3,oneof"`
}

type DeleteAttestationRequest_ContentHash struct {
	ContentHash string `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3,oneof"`
}

func (*DeleteAttestationRequest_AttestationId) isDeleteAttestationRequest_Identifier() {}

func (*DeleteAttestationRequest_ContentHash) isDeleteAttestationRequest_Identifier() {}

// DeleteAttestationResponse confirms deletion.
type DeleteAttestationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttestationResponse) Reset() {
	*x = DeleteAttestationResponse{}
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttestationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttestationResponse) ProtoMessage() {}

func (x *DeleteAttestationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttestationResponse.ProtoReflect.Descriptor instead.
func (*DeleteAttestationResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_stash_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAttestationResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// UpdateAttestationRequest updates attestation metadata.
type UpdateAttestationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Namespace (empty string = default namespace).
	Namespace     string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	AttestationId string `protobuf:"bytes,2,opt,name=attestation_id,json=attestationId,proto3" json:"attestation_id,omitempty"` // Future: metadata updates
	// Organization ID (required, must be valid DNS hostname).
	OrgId         string `protobuf:"bytes,10,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAttestationRequest) Reset() {
	*x = UpdateAttestationRequest{}
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAttestationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAttestationRequest) ProtoMessage() {}

func (x *UpdateAttestationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAttestationRequest.ProtoReflect.Descriptor instead.
func (*UpdateAttestationRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_stash_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAttestationRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UpdateAttestationRequest) GetAttestationId() string {
	if x != nil {
		return x.AttestationId
	}
	return ""
}

func (x *UpdateAttestationRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// UpdateAttestationResponse confirms update.
type UpdateAttestationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAttestationResponse) Reset() {
	*x = UpdateAttestationResponse{}
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAttestationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAttestationResponse) ProtoMessage() {}

func (x *UpdateAttestationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAttestationResponse.ProtoReflect.Descriptor instead.
func (*UpdateAttestationResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_stash_proto_rawDescGZIP(), []int{10}
}

// PushPoliciesRequest carries policy documents to store (max 100).
type PushPoliciesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Namespace for the policies (empty string = default namespace).
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Raw policy documents: bare policy JSON or an attestation envelope wrapping
	// one (a signed sigstore bundle or an unsigned DSSE).
	Policies [][]byte `protobuf:"bytes,2,rep,name=policies,proto3" json:"policies,omitempty"`
	// Organization ID (required, must be valid DNS hostname).
	OrgId         string `protobuf:"bytes,10,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushPoliciesRequest) Reset() {
	*x = PushPoliciesRequest{}
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPoliciesRequest) ProtoMessage() {}

func (x *PushPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPoliciesRequest.ProtoReflect.Descriptor instead.
func (*PushPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_stash_proto_rawDescGZIP(), []int{11}
}

func (x *PushPoliciesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PushPoliciesRequest) GetPolicies() [][]byte {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *PushPoliciesRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// PushPoliciesResponse reports the outcome of each submitted document, in order.
type PushPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PolicyResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushPoliciesResponse) Reset() {
	*x = PushPoliciesResponse{}
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPoliciesResponse) ProtoMessage() {}

func (x *PushPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPoliciesResponse.ProtoReflect.Descriptor instead.
func (*PushPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_stash_proto_rawDescGZIP(), []int{12}
}

func (x *PushPoliciesResponse) GetResults() []*PolicyResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// AppendPolicyRequest stores one document as the next version of a lineage.
type AppendPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Namespace (empty string = default namespace).
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// The lineage to append to. Created if it does not exist.
	LineageId string `protobuf:"bytes,2,opt,name=lineage_id,json=lineageId,proto3" json:"lineage_id,omitempty"`
	// The policy document.
	Policy []byte `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`
	// Organization ID (required, must be valid DNS hostname).
	OrgId         string `protobuf:"bytes,10,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendPolicyRequest) Reset() {
	*x = AppendPolicyRequest{}
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendPolicyRequest) ProtoMessage() {}

func (x *AppendPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendPolicyRequest.ProtoReflect.Descriptor instead.
func (*AppendPolicyRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_stash_proto_rawDescGZIP(), []int{13}
}

func (x *AppendPolicyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AppendPolicyRequest) GetLineageId() string {
	if x != nil {
		return x.LineageId
	}
	return ""
}

func (x *AppendPolicyRequest) GetPolicy() []byte {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *AppendPolicyRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// AppendPolicyResponse reports the outcome of an append.
type AppendPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *PolicyResult          `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendPolicyResponse) Reset() {
	*x = AppendPolicyResponse{}
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendPolicyResponse) ProtoMessage() {}

func (x *AppendPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendPolicyResponse.ProtoReflect.Descriptor instead.
func (*AppendPolicyResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_stash_proto_rawDescGZIP(), []int{14}
}

func (x *AppendPolicyResponse) GetResult() *PolicyResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// GetPolicyRequest retrieves a policy version.
type GetPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Namespace (empty string = default namespace).
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// The lineage to read.
	LineageId string `protobuf:"bytes,2,opt,name=lineage_id,json=lineageId,proto3" json:"lineage_id,omitempty"`
	// The version to read. When absent, the lineage's latest version is returned;
	// versions are 0-based, so an explicit 0 is version 0, not "latest".
	Version *int64 `protobuf:"varint,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	// If true, only return the raw stored document.
	RawOnly bool `protobuf:"varint,4,opt,name=raw_only,json=rawOnly,proto3" json:"raw_only,omitempty"`
	// Organization ID (required, must be valid DNS hostname).
	OrgId         string `protobuf:"bytes,10,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyRequest) Reset() {
	*x = GetPolicyRequest{}
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyRequest) ProtoMessage() {}

func (x *GetPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_stash_proto_rawDescGZIP(), []int{15}
}

func (x *GetPolicyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetPolicyRequest) GetLineageId() string {
	if x != nil {
		return x.LineageId
	}
	return ""
}

func (x *GetPolicyRequest) GetVersion() int64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *GetPolicyRequest) GetRawOnly() bool {
	if x != nil {
		return x.RawOnly
	}
	return false
}

func (x *GetPolicyRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// GetPolicyResponse carries a policy version and its stored bytes.
type GetPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	Raw           []byte                 `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"` // the stored policy document
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyResponse) Reset() {
	*x = GetPolicyResponse{}
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyResponse) ProtoMessage() {}

func (x *GetPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetPolicyResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_stash_proto_rawDescGZIP(), []int{16}
}

func (x *GetPolicyResponse) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *GetPolicyResponse) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

// DeletePolicyRequest removes a lineage or one of its versions.
type DeletePolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Namespace (empty string = default namespace).
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// The lineage to delete from.
	LineageId string `protobuf:"bytes,2,opt,name=lineage_id,json=lineageId,proto3" json:"lineage_id,omitempty"`
	// The version to delete. When absent the whole lineage (every version) is
	// deleted; when present only that 0-based version is deleted.
	Version *int64 `protobuf:"varint,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	// Organization ID (required, must be valid DNS hostname).
	OrgId         string `protobuf:"bytes,10,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyRequest) Reset() {
	*x = DeletePolicyRequest{}
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyRequest) ProtoMessage() {}

func (x *DeletePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyRequest.ProtoReflect.Descriptor instead.
func (*DeletePolicyRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_stash_proto_rawDescGZIP(), []int{17}
}

func (x *DeletePolicyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeletePolicyRequest) GetLineageId() string {
	if x != nil {
		return x.LineageId
	}
	return ""
}

func (x *DeletePolicyRequest) GetVersion() int64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *DeletePolicyRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// DeletePolicyResponse reports how many versions were deleted.
type DeletePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       int64                  `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyResponse) Reset() {
	*x = DeletePolicyResponse{}
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyResponse) ProtoMessage() {}

func (x *DeletePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyResponse.ProtoReflect.Descriptor instead.
func (*DeletePolicyResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_stash_proto_rawDescGZIP(), []int{18}
}

func (x *DeletePolicyResponse) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

// HealthCheckRequest checks service health.
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_stash_proto_rawDescGZIP(), []int{19}
}

// HealthCheckResponse contains health status.
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                                                                   // "healthy" or "unhealthy"
	Components    map[string]string      `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Component health details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_stash_v1_stash_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_stash_v1_stash_proto_rawDescGZIP(), []int{20}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetComponents() map[string]string {
	if x != nil {
		return x.Components
	}
	return nil
}

var File_carabiner_stash_v1_stash_proto protoreflect.FileDescriptor

const file_carabiner_stash_v1_stash_proto_rawDesc = "" +
	"\n" +
	"\x1ecarabiner/stash/v1/stash.proto\x12\x12carabiner.stash.v1\x1a$carabiner/stash/v1/attestation.proto\x1a carabiner/stash/v1/filters.proto\x1a\x1fcarabiner/stash/v1/policy.proto\x1a\"carabiner/stash/v1/publickey.proto\"t\n" +
	"\x19UploadAttestationsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\"\n" +
	"\fattestations\x18\x02 \x03(\fR\fattestations\x12\x15\n" +
	"\x06org_id\x18\n" +
	" \x01(\tR\x05orgId\"]\n" +
	"\x1aUploadAttestationsResponse\x12?\n" +
	"\aresults\x18\x01 \x03(\v2%.carabiner.stash.v1.AttestationResultR\aresults\"\xc3\x01\n" +
	"\x11AttestationResult\x12%\n" +
	"\x0eattestation_id\x18\x01 \x01(\tR\rattestationId\x12!\n" +
	"\fcontent_hash\x18\x02 \x01(\tR\vcontentHash\x12\x16\n" +
	"\x06stored\x18\x03 \x01(\bR\x06stored\x12\x1c\n" +
	"\tvalidated\x18\x04 \x01(\bR\tvalidated\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x18\n" +
	"\aexisted\x18\x06 \x01(\bR\aexisted\"\x93\x02\n" +
	"\x15GetAttestationRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12'\n" +
	"\x0eattestation_id\x18\x02 \x01(\tH\x00R\rattestationId\x12#\n" +
	"\fcontent_hash\x18\x03 \x01(\tH\x00R\vcontentHash\x12'\n" +
	"\x0epredicate_hash\x18\x04 \x01(\tH\x00R\rpredicateHash\x12\x19\n" +
	"\braw_only\x18\x05 \x01(\bR\arawOnly\x12%\n" +
	"\x0epredicate_only\x18\x06 \x01(\bR\rpredicateOnly\x12\x15\n" +
	"\x06org_id\x18\n" +
	" \x01(\tR\x05orgIdB\f\n" +
	"\n" +
	"identifier\"\xa9\x01\n" +
	"\x16GetAttestationResponse\x12A\n" +
	"\vattestation\x18\x01 \x01(\v2\x1f.carabiner.stash.v1.AttestationR\vattestation\x12'\n" +
	"\x0fraw_attestation\x18\x02 \x01(\fR\x0erawAttestation\x12#\n" +
	"\rraw_predicate\x18\x03 \x01(\fR\frawPredicate\"\xb9\x01\n" +
	"\x17ListAttestationsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x125\n" +
	"\afilters\x18\x02 \x01(\v2\x1b.carabiner.stash.v1.FiltersR\afilters\x122\n" +
	"\x06cursor\x18\x03 \x01(\v2\x1a.carabiner.stash.v1.CursorR\x06cursor\x12\x15\n" +
	"\x06org_id\x18\n" +
	" \x01(\tR\x05orgId\"\x9c\x01\n" +
	"\x18ListAttestationsResponse\x12C\n" +
	"\fattestations\x18\x01 \x03(\v2\x1f.carabiner.stash.v1.AttestationR\fattestations\x12;\n" +
	"\vnext_cursor\x18\x02 \x01(\v2\x1a.carabiner.stash.v1.CursorR\n" +
	"nextCursor\"\xab\x01\n" +
	"\x18DeleteAttestationRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12'\n" +
	"\x0eattestation_id\x18\x02 \x01(\tH\x00R\rattestationId\x12#\n" +
	"\fcontent_hash\x18\x03 \x01(\tH\x00R\vcontentHash\x12\x15\n" +
	"\x06org_id\x18\n" +
	" \x01(\tR\x05orgIdB\f\n" +
	"\n" +
	"identifier\"5\n" +
	"\x19DeleteAttestationResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"v\n" +
	"\x18UpdateAttestationRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12%\n" +
	"\x0eattestation_id\x18\x02 \x01(\tR\rattestationId\x12\x15\n" +
	"\x06org_id\x18\n" +
	" \x01(\tR\x05orgId\"\x1b\n" +
	"\x19UpdateAttestationResponse\"f\n" +
	"\x13PushPoliciesRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bpolicies\x18\x02 \x03(\fR\bpolicies\x12\x15\n" +
	"\x06org_id\x18\n" +
	" \x01(\tR\x05orgId\"R\n" +
	"\x14PushPoliciesResponse\x12:\n" +
	"\aresults\x18\x01 \x03(\v2 .carabiner.stash.v1.PolicyResultR\aresults\"\x81\x01\n" +
	"\x13AppendPolicyRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"lineage_id\x18\x02 \x01(\tR\tlineageId\x12\x16\n" +
	"\x06policy\x18\x03 \x01(\fR\x06policy\x12\x15\n" +
	"\x06org_id\x18\n" +
	" \x01(\tR\x05orgId\"P\n" +
	"\x14AppendPolicyResponse\x128\n" +
	"\x06result\x18\x01 \x01(\v2 .carabiner.stash.v1.PolicyResultR\x06result\"\xac\x01\n" +
	"\x10GetPolicyRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"lineage_id\x18\x02 \x01(\tR\tlineageId\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\x03H\x00R\aversion\x88\x01\x01\x12\x19\n" +
	"\braw_only\x18\x04 \x01(\bR\arawOnly\x12\x15\n" +
	"\x06org_id\x18\n" +
	" \x01(\tR\x05orgIdB\n" +
	"\n" +
	"\b_version\"Y\n" +
	"\x11GetPolicyResponse\x122\n" +
	"\x06policy\x18\x01 \x01(\v2\x1a.carabiner.stash.v1.PolicyR\x06policy\x12\x10\n" +
	"\x03raw\x18\x02 \x01(\fR\x03raw\"\x94\x01\n" +
	"\x13DeletePolicyRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"lineage_id\x18\x02 \x01(\tR\tlineageId\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\x03H\x00R\aversion\x88\x01\x01\x12\x15\n" +
	"\x06org_id\x18\n" +
	" \x01(\tR\x05orgIdB\n" +
	"\n" +
	"\b_version\"0\n" +
	"\x14DeletePolicyResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x03R\adeleted\"\x14\n" +
	"\x12HealthCheckRequest\"\xc5\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12W\n" +
	"\n" +
	"components\x18\x02 \x03(\v27.carabiner.stash.v1.HealthCheckResponse.ComponentsEntryR\n" +
	"components\x1a=\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xe3\n" +
	"\n" +
	"\fStashService\x12s\n" +
	"\x12UploadAttestations\x12-.carabiner.stash.v1.UploadAttestationsRequest\x1a..carabiner.stash.v1.UploadAttestationsResponse\x12g\n" +
	"\x0eGetAttestation\x12).carabiner.stash.v1.GetAttestationRequest\x1a*.carabiner.stash.v1.GetAttestationResponse\x12m\n" +
	"\x10ListAttestations\x12+.carabiner.stash.v1.ListAttestationsRequest\x1a,.carabiner.stash.v1.ListAttestationsResponse\x12p\n" +
	"\x11DeleteAttestation\x12,.carabiner.stash.v1.DeleteAttestationRequest\x1a-.carabiner.stash.v1.DeleteAttestationResponse\x12p\n" +
	"\x11UpdateAttestation\x12,.carabiner.stash.v1.UpdateAttestationRequest\x1a-.carabiner.stash.v1.UpdateAttestationResponse\x12j\n" +
	"\x0fUploadPublicKey\x12*.carabiner.stash.v1.UploadPublicKeyRequest\x1a+.carabiner.stash.v1.UploadPublicKeyResponse\x12j\n" +
	"\x0fDeletePublicKey\x12*.carabiner.stash.v1.DeletePublicKeyRequest\x1a+.carabiner.stash.v1.DeletePublicKeyResponse\x12g\n" +
	"\x0eListPublicKeys\x12).carabiner.stash.v1.ListPublicKeysRequest\x1a*.carabiner.stash.v1.ListPublicKeysResponse\x12a\n" +
	"\fPushPolicies\x12'.carabiner.stash.v1.PushPoliciesRequest\x1a(.carabiner.stash.v1.PushPoliciesResponse\x12a\n" +
	"\fAppendPolicy\x12'.carabiner.stash.v1.AppendPolicyRequest\x1a(.carabiner.stash.v1.AppendPolicyResponse\x12X\n" +
	"\tGetPolicy\x12$.carabiner.stash.v1.GetPolicyRequest\x1a%.carabiner.stash.v1.GetPolicyResponse\x12a\n" +
	"\fDeletePolicy\x12'.carabiner.stash.v1.DeletePolicyRequest\x1a(.carabiner.stash.v1.DeletePolicyResponse\x12^\n" +
	"\vHealthCheck\x12&.carabiner.stash.v1.HealthCheckRequest\x1a'.carabiner.stash.v1.HealthCheckResponseB\xc9\x01\n" +
	"\x16com.carabiner.stash.v1B\n" +
	"StashProtoP\x01Z9github.com/carabiner-dev/stash/carabiner/stash/v1;stashv1\xa2\x02\x03CSX\xaa\x02\x12Carabiner.Stash.V1\xca\x02\x12Carabiner\\Stash\\V1\xe2\x02\x1eCarabiner\\Stash\\V1\\GPBMetadata\xea\x02\x14Carabiner::Stash::V1b\x06proto3"

var (
	file_carabiner_stash_v1_stash_proto_rawDescOnce sync.Once
	file_carabiner_stash_v1_stash_proto_rawDescData []byte
)

func file_carabiner_stash_v1_stash_proto_rawDescGZIP() []byte {
	file_carabiner_stash_v1_stash_proto_rawDescOnce.Do(func() {
		file_carabiner_stash_v1_stash_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carabiner_stash_v1_stash_proto_rawDesc), len(file_carabiner_stash_v1_stash_proto_rawDesc)))
	})
	return file_carabiner_stash_v1_stash_proto_rawDescData
}

var file_carabiner_stash_v1_stash_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_carabiner_stash_v1_stash_proto_goTypes = []any{
	(*UploadAttestationsRequest)(nil),  // 0: carabiner.stash.v1.UploadAttestationsRequest
	(*UploadAttestationsResponse)(nil), // 1: carabiner.stash.v1.UploadAttestationsResponse
	(*AttestationResult)(nil),          // 2: carabiner.stash.v1.AttestationResult
	(*GetAttestationRequest)(nil),      // 3: carabiner.stash.v1.GetAttestationRequest
	(*GetAttestationResponse)(nil),     // 4: carabiner.stash.v1.GetAttestationResponse
	(*ListAttestationsRequest)(nil),    // 5: carabiner.stash.v1.ListAttestationsRequest
	(*ListAttestationsResponse)(nil),   // 6: carabiner.stash.v1.ListAttestationsResponse
	(*DeleteAttestationRequest)(nil),   // 7: carabiner.stash.v1.DeleteAttestationRequest
	(*DeleteAttestationResponse)(nil),  // 8: carabiner.stash.v1.DeleteAttestationResponse
	(*UpdateAttestationRequest)(nil),   // 9: carabiner.stash.v1.UpdateAttestationRequest
	(*UpdateAttestationResponse)(nil),  // 10: carabiner.stash.v1.UpdateAttestationResponse
	(*PushPoliciesRequest)(nil),        // 11: carabiner.stash.v1.PushPoliciesRequest
	(*PushPoliciesResponse)(nil),       // 12: carabiner.stash.v1.PushPoliciesResponse
	(*AppendPolicyRequest)(nil),        // 13: carabiner.stash.v1.AppendPolicyRequest
	(*AppendPolicyResponse)(nil),       // 14: carabiner.stash.v1.AppendPolicyResponse
	(*GetPolicyRequest)(nil),           // 15: carabiner.stash.v1.GetPolicyRequest
	(*GetPolicyResponse)(nil),          // 16: carabiner.stash.v1.GetPolicyResponse
	(*DeletePolicyRequest)(nil),        // 17: carabiner.stash.v1.DeletePolicyRequest
	(*DeletePolicyResponse)(nil),       // 18: carabiner.stash.v1.DeletePolicyResponse
	(*HealthCheckRequest)(nil),         // 19: carabiner.stash.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),        // 20: carabiner.stash.v1.HealthCheckResponse
	nil,                                // 21: carabiner.stash.v1.HealthCheckResponse.ComponentsEntry
	(*Attestation)(nil),                // 22: carabiner.stash.v1.Attestation
	(*Filters)(nil),                    // 23: carabiner.stash.v1.Filters
	(*Cursor)(nil),                     // 24: carabiner.stash.v1.Cursor
	(*PolicyResult)(nil),               // 25: carabiner.stash.v1.PolicyResult
	(*Policy)(nil),                     // 26: carabiner.stash.v1.Policy
	(*UploadPublicKeyRequest)(nil),     // 27: carabiner.stash.v1.UploadPublicKeyRequest
	(*DeletePublicKeyRequest)(nil),     // 28: carabiner.stash.v1.DeletePublicKeyRequest
	(*ListPublicKeysRequest)(nil),      // 29: carabiner.stash.v1.ListPublicKeysRequest
	(*UploadPublicKeyResponse)(nil),    // 30: carabiner.stash.v1.UploadPublicKeyResponse
	(*DeletePublicKeyResponse)(nil),    // 31: carabiner.stash.v1.DeletePublicKeyResponse
	(*ListPublicKeysResponse)(nil),     // 32: carabiner.stash.v1.ListPublicKeysResponse
}
var file_carabiner_stash_v1_stash_proto_depIdxs = []int32{
	2,  // 0: carabiner.stash.v1.UploadAttestationsResponse.results:type_name -> carabiner.stash.v1.AttestationResult
	22, // 1: carabiner.stash.v1.GetAttestationResponse.attestation:type_name -> carabiner.stash.v1.Attestation
	23, // 2: carabiner.stash.v1.ListAttestationsRequest.filters:type_name -> carabiner.stash.v1.Filters
	24, // 3: carabiner.stash.v1.ListAttestationsRequest.cursor:type_name -> carabiner.stash.v1.Cursor
	22, // 4: carabiner.stash.v1.ListAttestationsResponse.attestations:type_name -> carabiner.stash.v1.Attestation
	24, // 5: carabiner.stash.v1.ListAttestationsResponse.next_cursor:type_name -> carabiner.stash.v1.Cursor
	25, // 6: carabiner.stash.v1.PushPoliciesResponse.results:type_name -> carabiner.stash.v1.PolicyResult
	25, // 7: carabiner.stash.v1.AppendPolicyResponse.result:type_name -> carabiner.stash.v1.PolicyResult
	26, // 8: carabiner.stash.v1.GetPolicyResponse.policy:type_name -> carabiner.stash.v1.Policy
	21, // 9: carabiner.stash.v1.HealthCheckResponse.components:type_name -> carabiner.stash.v1.HealthCheckResponse.ComponentsEntry
	0,  // 10: carabiner.stash.v1.StashService.UploadAttestations:input_type -> carabiner.stash.v1.UploadAttestationsRequest
	3,  // 11: carabiner.stash.v1.StashService.GetAttestation:input_type -> carabiner.stash.v1.GetAttestationRequest
	5,  // 12: carabiner.stash.v1.StashService.ListAttestations:input_type -> carabiner.stash.v1.ListAttestationsRequest
	7,  // 13: carabiner.stash.v1.StashService.DeleteAttestation:input_type -> carabiner.stash.v1.DeleteAttestationRequest
	9,  // 14: carabiner.stash.v1.StashService.UpdateAttestation:input_type -> carabiner.stash.v1.UpdateAttestationRequest
	27, // 15: carabiner.stash.v1.StashService.UploadPublicKey:input_type -> carabiner.stash.v1.UploadPublicKeyRequest
	28, // 16: carabiner.stash.v1.StashService.DeletePublicKey:input_type -> carabiner.stash.v1.DeletePublicKeyRequest
	29, // 17: carabiner.stash.v1.StashService.ListPublicKeys:input_type -> carabiner.stash.v1.ListPublicKeysRequest
	11, // 18: carabiner.stash.v1.StashService.PushPolicies:input_type -> carabiner.stash.v1.PushPoliciesRequest
	13, // 19: carabiner.stash.v1.StashService.AppendPolicy:input_type -> carabiner.stash.v1.AppendPolicyRequest
	15, // 20: carabiner.stash.v1.StashService.GetPolicy:input_type -> carabiner.stash.v1.GetPolicyRequest
	17, // 21: carabiner.stash.v1.StashService.DeletePolicy:input_type -> carabiner.stash.v1.DeletePolicyRequest
	19, // 22: carabiner.stash.v1.StashService.HealthCheck:input_type -> carabiner.stash.v1.HealthCheckRequest
	1,  // 23: carabiner.stash.v1.StashService.UploadAttestations:output_type -> carabiner.stash.v1.UploadAttestationsResponse
	4,  // 24: carabiner.stash.v1.StashService.GetAttestation:output_type -> carabiner.stash.v1.GetAttestationResponse
	6,  // 25: carabiner.stash.v1.StashService.ListAttestations:output_type -> carabiner.stash.v1.ListAttestationsResponse
	8,  // 26: carabiner.stash.v1.StashService.DeleteAttestation:output_type -> carabiner.stash.v1.DeleteAttestationResponse
	10, // 27: carabiner.stash.v1.StashService.UpdateAttestation:output_type -> carabiner.stash.v1.UpdateAttestationResponse
	30, // 28: carabiner.stash.v1.StashService.UploadPublicKey:output_type -> carabiner.stash.v1.UploadPublicKeyResponse
	31, // 29: carabiner.stash.v1.StashService.DeletePublicKey:output_type -> carabiner.stash.v1.DeletePublicKeyResponse
	32, // 30: carabiner.stash.v1.StashService.ListPublicKeys:output_type -> carabiner.stash.v1.ListPublicKeysResponse
	12, // 31: carabiner.stash.v1.StashService.PushPolicies:output_type -> carabiner.stash.v1.PushPoliciesResponse
	14, // 32: carabiner.stash.v1.StashService.AppendPolicy:output_type -> carabiner.stash.v1.AppendPolicyResponse
	16, // 33: carabiner.stash.v1.StashService.GetPolicy:output_type -> carabiner.stash.v1.GetPolicyResponse
	18, // 34: carabiner.stash.v1.StashService.DeletePolicy:output_type -> carabiner.stash.v1.DeletePolicyResponse
	20, // 35: carabiner.stash.v1.StashService.HealthCheck:output_type -> carabiner.stash.v1.HealthCheckResponse
	23, // [23:36] is the sub-list for method output_type
	10, // [10:23] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_carabiner_stash_v1_stash_proto_init() }
func file_carabiner_stash_v1_stash_proto_init() {
	if File_carabiner_stash_v1_stash_proto != nil {
		return
	}
	file_carabiner_stash_v1_attestation_proto_init()
	file_carabiner_stash_v1_filters_proto_init()
	file_carabiner_stash_v1_policy_proto_init()
	file_carabiner_stash_v1_publickey_proto_init()
	file_carabiner_stash_v1_stash_proto_msgTypes[3].OneofWrappers = []any{
		(*GetAttestationRequest_AttestationId)(nil),
		(*GetAttestationRequest_ContentHash)(nil),
		(*GetAttestationRequest_PredicateHash)(nil),
	}
	file_carabiner_stash_v1_stash_proto_msgTypes[7].OneofWrappers = []any{
		(*DeleteAttestationRequest_AttestationId)(nil),
		(*DeleteAttestationRequest_ContentHash)(nil),
	}
	file_carabiner_stash_v1_stash_proto_msgTypes[15].OneofWrappers = []any{}
	file_carabiner_stash_v1_stash_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carabiner_stash_v1_stash_proto_rawDesc), len(file_carabiner_stash_v1_stash_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_carabiner_stash_v1_stash_proto_goTypes,
		DependencyIndexes: file_carabiner_stash_v1_stash_proto_depIdxs,
		MessageInfos:      file_carabiner_stash_v1_stash_proto_msgTypes,
	}.Build()
	File_carabiner_stash_v1_stash_proto = out.File
	file_carabiner_stash_v1_stash_proto_goTypes = nil
	file_carabiner_stash_v1_stash_proto_depIdxs = nil
}
